---
version: 0.3.4.3
slug: tzb-silabs-flasher
name: TubesZB Silicon Labs FW Flasher
description: TubesZB Silicon Labs firmware flasher add-on
url: >
  https://tube0013/tubeszb_addons/tree/master/tzb-silabs-flasher
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: false
hassio_api: true
image: "ghcr.io/tube0013/{arch}-addon-tzb-silabs-flasher"
init: false
options:
  network_device: null
  device: null
  device_type: false
  firmware_url: str?
  bootloader_baudrate: "115200"
  flow_control: false
  verbose: false
schema:
  network_device: str?
  device: device(subsystem=tty)?
  device_type: bool?
  firmware_url: str?
  bootloader_baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  verbose: bool?
stage: experimental
startup: once
boot: manual
